export interface City {
  name: string
  country: string
  lat: number
  lon: number
  tz: string
}

// Hand-picked cities guaranteeing at least one marker in every UTC offset
// band and continent, even in places too sparsely populated to make a
// population-ranked cut on their own.
const CURATED: City[] = [
  { name: 'London', country: 'UK', lat: 51.5074, lon: -0.1278, tz: 'Europe/London' },
  { name: 'Paris', country: 'France', lat: 48.8566, lon: 2.3522, tz: 'Europe/Paris' },
  { name: 'Berlin', country: 'Germany', lat: 52.52, lon: 13.405, tz: 'Europe/Berlin' },
  { name: 'Cairo', country: 'Egypt', lat: 30.0444, lon: 31.2357, tz: 'Africa/Cairo' },
  { name: 'Moscow', country: 'Russia', lat: 55.7558, lon: 37.6173, tz: 'Europe/Moscow' },
  { name: 'Istanbul', country: 'Turkey', lat: 41.0082, lon: 28.9784, tz: 'Europe/Istanbul' },
  { name: 'Dubai', country: 'UAE', lat: 25.2048, lon: 55.2708, tz: 'Asia/Dubai' },
  { name: 'New Delhi', country: 'India', lat: 28.6139, lon: 77.209, tz: 'Asia/Kolkata' },
  { name: 'Karachi', country: 'Pakistan', lat: 24.8607, lon: 67.0011, tz: 'Asia/Karachi' },
  { name: 'Dhaka', country: 'Bangladesh', lat: 23.8103, lon: 90.4125, tz: 'Asia/Dhaka' },
  { name: 'Bangkok', country: 'Thailand', lat: 13.7563, lon: 100.5018, tz: 'Asia/Bangkok' },
  { name: 'Singapore', country: 'Singapore', lat: 1.3521, lon: 103.8198, tz: 'Asia/Singapore' },
  { name: 'Beijing', country: 'China', lat: 39.9042, lon: 116.4074, tz: 'Asia/Shanghai' },
  { name: 'Hong Kong', country: 'China', lat: 22.3193, lon: 114.1694, tz: 'Asia/Hong_Kong' },
  { name: 'Tokyo', country: 'Japan', lat: 35.6762, lon: 139.6503, tz: 'Asia/Tokyo' },
  { name: 'Seoul', country: 'South Korea', lat: 37.5665, lon: 126.978, tz: 'Asia/Seoul' },
  { name: 'Sydney', country: 'Australia', lat: -33.8688, lon: 151.2093, tz: 'Australia/Sydney' },
  { name: 'Perth', country: 'Australia', lat: -31.9505, lon: 115.8605, tz: 'Australia/Perth' },
  { name: 'Auckland', country: 'New Zealand', lat: -36.8485, lon: 174.7633, tz: 'Pacific/Auckland' },
  { name: 'Honolulu', country: 'USA', lat: 21.3069, lon: -157.8583, tz: 'Pacific/Honolulu' },
  { name: 'Anchorage', country: 'USA', lat: 61.2181, lon: -149.9003, tz: 'America/Anchorage' },
  { name: 'Los Angeles', country: 'USA', lat: 34.0522, lon: -118.2437, tz: 'America/Los_Angeles' },
  { name: 'Denver', country: 'USA', lat: 39.7392, lon: -104.9903, tz: 'America/Denver' },
  { name: 'Chicago', country: 'USA', lat: 41.8781, lon: -87.6298, tz: 'America/Chicago' },
  { name: 'Mexico City', country: 'Mexico', lat: 19.4326, lon: -99.1332, tz: 'America/Mexico_City' },
  { name: 'New York', country: 'USA', lat: 40.7128, lon: -74.006, tz: 'America/New_York' },
  { name: 'Toronto', country: 'Canada', lat: 43.6532, lon: -79.3832, tz: 'America/Toronto' },
  { name: 'Bogotá', country: 'Colombia', lat: 4.711, lon: -74.0721, tz: 'America/Bogota' },
  { name: 'Lima', country: 'Peru', lat: -12.0464, lon: -77.0428, tz: 'America/Lima' },
  { name: 'Santiago', country: 'Chile', lat: -33.4489, lon: -70.6693, tz: 'America/Santiago' },
  { name: 'São Paulo', country: 'Brazil', lat: -23.5558, lon: -46.6396, tz: 'America/Sao_Paulo' },
  { name: 'Buenos Aires', country: 'Argentina', lat: -34.6037, lon: -58.3816, tz: 'America/Argentina/Buenos_Aires' },
  { name: 'Reykjavik', country: 'Iceland', lat: 64.1466, lon: -21.9426, tz: 'Atlantic/Reykjavik' },
  { name: 'Lagos', country: 'Nigeria', lat: 6.5244, lon: 3.3792, tz: 'Africa/Lagos' },
  { name: 'Johannesburg', country: 'South Africa', lat: -26.2041, lon: 28.0473, tz: 'Africa/Johannesburg' },
  { name: 'Nairobi', country: 'Kenya', lat: -1.2921, lon: 36.8219, tz: 'Africa/Nairobi' },
]

// The next-most-populous cities worldwide (from the same city-timezones data
// used for search — see allCities.ts), precomputed at build time and checked
// in as a static list. This keeps cities.ts free of any runtime dependency
// on the ~2MB dataset package, since the globe needs these markers
// synchronously at first paint; allCities.ts lazy-loads the full package
// separately for search and nearest-city lookups.
const TOP_BY_POPULATION: City[] = [
{ name: "Mumbai, Maharashtra", country: "India", lat: 19.017, lon: 72.857, tz: "Asia/Kolkata" },
  { name: "Mexico City, Distrito Federal", country: "Mexico", lat: 19.4424, lon: -99.131, tz: "America/Mexico_City" },
  { name: "Shanghai", country: "China", lat: 31.2165, lon: 121.4365, tz: "Asia/Shanghai" },
  { name: "Sao Paulo, São Paulo", country: "Brazil", lat: -23.5587, lon: -46.625, tz: "America/Sao_Paulo" },
  { name: "New York", country: "United States of America", lat: 40.75, lon: -73.98, tz: "America/New_York" },
  { name: "Karachi, Sind", country: "Pakistan", lat: 24.87, lon: 66.99, tz: "Asia/Karachi" },
  { name: "Buenos Aires, Ciudad de Buenos Aires", country: "Argentina", lat: -34.6025, lon: -58.3975, tz: "America/Argentina/Buenos_Aires" },
  { name: "Delhi", country: "India", lat: 28.67, lon: 77.23, tz: "Asia/Kolkata" },
  { name: "Moscow, Moskva", country: "Russia", lat: 55.7522, lon: 37.6155, tz: "Europe/Moscow" },
  { name: "Cairo, Al Qahirah", country: "Egypt", lat: 30.05, lon: 31.25, tz: "Africa/Cairo" },
  { name: "Kolkata, West Bengal", country: "India", lat: 22.495, lon: 88.3247, tz: "Asia/Kolkata" },
  { name: "Jakarta, Jakarta Raya", country: "Indonesia", lat: -6.1744, lon: 106.8294, tz: "Asia/Jakarta" },
  { name: "Los Angeles, California", country: "United States of America", lat: 33.99, lon: -118.18, tz: "America/Los_Angeles" },
  { name: "London, Westminster", country: "United Kingdom", lat: 51.5, lon: -0.1167, tz: "Europe/London" },
  { name: "Tehran", country: "Iran", lat: 35.6719, lon: 51.4243, tz: "Asia/Tehran" },
  { name: "Manila, Metropolitan Manila", country: "Philippines", lat: 14.6042, lon: 120.9822, tz: "Asia/Manila" },
  { name: "Bogota", country: "Colombia", lat: 4.5964, lon: -74.0833, tz: "America/Bogota" },
  { name: "Osaka", country: "Japan", lat: 34.75, lon: 135.4601, tz: "Asia/Tokyo" },
  { name: "Rio de Janeiro", country: "Brazil", lat: -22.925, lon: -43.225, tz: "America/Sao_Paulo" },
  { name: "Kinshasa, Kinshasa City", country: "Congo (Kinshasa)", lat: -4.3297, lon: 15.315, tz: "Africa/Kinshasa" },
  { name: "Lahore, Punjab", country: "Pakistan", lat: 31.56, lon: 74.35, tz: "Asia/Karachi" },
  { name: "Guangzhou, Guangdong", country: "China", lat: 23.145, lon: 113.325, tz: "Asia/Shanghai" },
  { name: "Bengaluru, Karnataka", country: "India", lat: 12.97, lon: 77.56, tz: "Asia/Kolkata" },
  { name: "Chicago, Illinois", country: "United States of America", lat: 41.83, lon: -87.7501, tz: "America/Chicago" },
  { name: "Bangkok, Bangkok Metropolis", country: "Thailand", lat: 13.75, lon: 100.5166, tz: "Asia/Bangkok" },
  { name: "Hong Kong", country: "Hong Kong S.A.R.", lat: 22.305, lon: 114.185, tz: "Asia/Hong_Kong" },
  { name: "Chennai, Tamil Nadu", country: "India", lat: 13.09, lon: 80.28, tz: "Asia/Kolkata" },
  { name: "Wuhan, Hubei", country: "China", lat: 30.58, lon: 114.27, tz: "Asia/Shanghai" },
  { name: "Tianjin", country: "China", lat: 39.13, lon: 117.2, tz: "Asia/Shanghai" },
  { name: "Sydney, New South Wales", country: "Australia", lat: -33.92, lon: 151.1852, tz: "Australia/Sydney" },
  { name: "Chongqing", country: "China", lat: 29.565, lon: 106.595, tz: "Asia/Chongqing" },
  { name: "Baghdad", country: "Iraq", lat: 33.3386, lon: 44.3939, tz: "Asia/Baghdad" },
  { name: "Hyderabad, Andhra Pradesh", country: "India", lat: 17.4, lon: 78.48, tz: "Asia/Kolkata" },
  { name: "Paris, Île-de-France", country: "France", lat: 48.8667, lon: 2.3333, tz: "Europe/Paris" },
  { name: "Melbourne, Victoria", country: "Australia", lat: -37.82, lon: 144.975, tz: "Australia/Melbourne" },
  { name: "Taipei, Taipei City", country: "Taiwan", lat: 25.0358, lon: 121.5683, tz: "Asia/Taipei" },
  { name: "Toronto, Ontario", country: "Canada", lat: 43.7, lon: -79.42, tz: "America/Toronto" },
  { name: "Ahmedabad, Dadra and Nagar Haveli", country: "India", lat: 23.0301, lon: 72.58, tz: "Asia/Kolkata" },
  { name: "Dongguan, Guangdong", country: "China", lat: 23.0489, lon: 113.7447, tz: "Asia/Shanghai" },
  { name: "Ho Chi Minh City", country: "Vietnam", lat: 10.78, lon: 106.695, tz: "Asia/Ho_Chi_Minh" },
  { name: "Riyadh, Ar Riyad", country: "Saudi Arabia", lat: 24.6408, lon: 46.7727, tz: "Asia/Riyadh" },
  { name: "Shenzhen, Guangdong", country: "China", lat: 22.5524, lon: 114.1221, tz: "Asia/Shanghai" },
  { name: "Chittagong", country: "Bangladesh", lat: 22.33, lon: 91.8, tz: "Asia/Dhaka" },
  { name: "Shenyeng, Liaoning", country: "China", lat: 41.805, lon: 123.45, tz: "Asia/Shanghai" },
  { name: "Houston, Texas", country: "United States of America", lat: 29.82, lon: -95.34, tz: "America/Chicago" },
  { name: "Chengdu, Sichuan", country: "China", lat: 30.67, lon: 104.07, tz: "Asia/Chongqing" },
  { name: "St. Petersburg, City of St. Petersburg", country: "Russia", lat: 59.939, lon: 30.316, tz: "Europe/Moscow" },
  { name: "Alexandria, Al Iskandariyah", country: "Egypt", lat: 31.2, lon: 29.95, tz: "Africa/Cairo" },
  { name: "Belo Horizonte, Minas Gerais", country: "Brazil", lat: -19.915, lon: -43.915, tz: "America/Sao_Paulo" },
  { name: "Pune, Maharashtra", country: "India", lat: 18.53, lon: 73.85, tz: "Asia/Kolkata" },
  { name: "Yokohama, Kanagawa", country: "Japan", lat: 35.32, lon: 139.58, tz: "Asia/Tokyo" },
  { name: "Rangoon, Yangon", country: "Myanmar", lat: 16.7834, lon: 96.1667, tz: "Asia/Rangoon" },
  { name: "Xian, Shaanxi", country: "China", lat: 34.275, lon: 108.895, tz: "Asia/Chongqing" },
  { name: "Luanda", country: "Angola", lat: -8.8383, lon: 13.2344, tz: "Africa/Luanda" },
  { name: "Ankara", country: "Turkey", lat: 39.9272, lon: 32.8644, tz: "Europe/Istanbul" },
  { name: "Philadelphia, Pennsylvania", country: "United States of America", lat: 40, lon: -75.17, tz: "America/New_York" },
  { name: "Abidjan, Lagunes", country: "Ivory Coast", lat: 5.32, lon: -4.04, tz: "Africa/Abidjan" },
  { name: "Busan", country: "South Korea", lat: 35.0951, lon: 129.01, tz: "Asia/Seoul" },
  { name: "Harbin, Heilongjiang", country: "China", lat: 45.75, lon: 126.65, tz: "Asia/Harbin" },
  { name: "Nanjing, Jiangsu", country: "China", lat: 32.05, lon: 118.78, tz: "Asia/Shanghai" },
  { name: "Surat, Dadra and Nagar Haveli", country: "India", lat: 21.2, lon: 72.84, tz: "Asia/Kolkata" },
  { name: "Khartoum", country: "Sudan", lat: 15.5881, lon: 32.5342, tz: "Africa/Khartoum" },
  { name: "Hechi, Guangxi", country: "China", lat: 23.0965, lon: 109.6091, tz: "Asia/Chongqing" },
  { name: "Barcelona, Cataluña", country: "Spain", lat: 41.3833, lon: 2.1834, tz: "Europe/Madrid" },
  { name: "Casablanca, Grand Casablanca", country: "Morocco", lat: 33.6, lon: -7.6164, tz: "Africa/Casablanca" },
  { name: "Kabul", country: "Afghanistan", lat: 34.5167, lon: 69.1833, tz: "Asia/Kabul" },
  { name: "Kano", country: "Nigeria", lat: 12, lon: 8.52, tz: "Africa/Lagos" },
  { name: "Brasilia, Distrito Federal", country: "Brazil", lat: -15.7833, lon: -47.9161, tz: "America/Sao_Paulo" },
  { name: "Salvador, Bahia", country: "Brazil", lat: -12.97, lon: -38.48, tz: "America/Bahia" },
  { name: "Montréal, Québec", country: "Canada", lat: 45.5, lon: -73.5833, tz: "America/Montreal" },
  { name: "Dallas, Texas", country: "United States of America", lat: 32.82, lon: -96.84, tz: "America/Chicago" },
  { name: "Kanpur, Uttar Pradesh", country: "India", lat: 26.46, lon: 80.32, tz: "Asia/Kolkata" },
  { name: "Miami, Florida", country: "United States of America", lat: 25.7876, lon: -80.2241, tz: "America/New_York" },
  { name: "Fortaleza, Ceará", country: "Brazil", lat: -3.75, lon: -38.58, tz: "America/Fortaleza" },
  { name: "Jeddah, Makkah", country: "Saudi Arabia", lat: 21.5169, lon: 39.2192, tz: "Asia/Riyadh" },
  { name: "Haora, West Bengal", country: "India", lat: 22.5804, lon: 88.3299, tz: "Asia/Kolkata" },
  { name: "Addis Ababa", country: "Ethiopia", lat: 9.0333, lon: 38.7, tz: "Africa/Addis_Ababa" },
  { name: "Guadalajara, Jalisco", country: "Mexico", lat: 20.67, lon: -103.33, tz: "America/Mexico_City" },
  { name: "Hanoi, Thái Nguyên", country: "Vietnam", lat: 21.0333, lon: 105.85, tz: "Asia/Ho_Chi_Minh" },
  { name: "Pyongyang, P'yongyang", country: "North Korea", lat: 39.0194, lon: 125.7547, tz: "Asia/Pyongyang" },
  { name: "Santiago, Región Metropolitana de Santiago", country: "Chile", lat: -33.45, lon: -70.667, tz: "America/Santiago" },
  { name: "Changchun, Jilin", country: "China", lat: 43.865, lon: 125.34, tz: "Asia/Harbin" },
  { name: "Cape Town, Western Cape", country: "South Africa", lat: -33.92, lon: 18.435, tz: "Africa/Johannesburg" },
  { name: "New Taipei, New Taipei City", country: "Taiwan", lat: 25.0128, lon: 121.465, tz: "Asia/Taipei" },
  { name: "Taiyuan, Shanxi", country: "China", lat: 37.875, lon: 112.5451, tz: "Asia/Shanghai" },
  { name: "Jaipur, Rajasthan", country: "India", lat: 26.9211, lon: 75.81, tz: "Asia/Kolkata" },
  { name: "Dar es Salaam, Dar-Es-Salaam", country: "Tanzania", lat: -6.8, lon: 39.2683, tz: "Africa/Dar_es_Salaam" },
  { name: "Madrid, Comunidad de Madrid", country: "Spain", lat: 40.4, lon: -3.6834, tz: "Europe/Madrid" },
  { name: "Quezon City, Metropolitan Manila", country: "Philippines", lat: 14.6504, lon: 121.03, tz: "Asia/Manila" },
  { name: "Johannesburg, Gauteng", country: "South Africa", lat: -26.17, lon: 28.03, tz: "Africa/Johannesburg" },
  { name: "Durban, KwaZulu-Natal", country: "South Africa", lat: -29.865, lon: 30.98, tz: "Africa/Johannesburg" },
  { name: "Nagoya, Aichi", country: "Japan", lat: 35.155, lon: 136.915, tz: "Asia/Tokyo" },
  { name: "El Giza, Al Jizah", country: "Egypt", lat: 30.01, lon: 31.19, tz: "Africa/Cairo" },
  { name: "Algiers, Alger", country: "Algeria", lat: 36.7631, lon: 3.0506, tz: "Africa/Algiers" },
  { name: "Medellin, Antioquia", country: "Colombia", lat: 6.275, lon: -75.575, tz: "America/Bogota" },
  { name: "Porto Alegre, Rio Grande do Sul", country: "Brazil", lat: -30.05, lon: -51.2, tz: "America/Sao_Paulo" },
  { name: "Surabaya, Jawa Timur", country: "Indonesia", lat: -7.2492, lon: 112.7508, tz: "Asia/Jakarta" },
  { name: "Dalian, Liaoning", country: "China", lat: 38.9228, lon: 121.6298, tz: "Asia/Shanghai" },
  { name: "Lucknow, Uttar Pradesh", country: "India", lat: 26.855, lon: 80.915, tz: "Asia/Kolkata" },
  { name: "Recife, Pernambuco", country: "Brazil", lat: -8.0756, lon: -34.9156, tz: "America/Recife" },
  { name: "Faisalabad, Punjab", country: "Pakistan", lat: 31.41, lon: 73.11, tz: "Asia/Karachi" },
  { name: "Incheon, Inch'on-gwangyoksi", country: "South Korea", lat: 37.4761, lon: 126.6422, tz: "Asia/Seoul" },
  { name: "Dakar", country: "Senegal", lat: 14.7158, lon: -17.4731, tz: "Africa/Dakar" },
  { name: "Boston, Massachusetts", country: "United States of America", lat: 42.33, lon: -71.07, tz: "America/New_York" },
  { name: "Detroit, Michigan", country: "United States of America", lat: 42.33, lon: -83.0801, tz: "America/Detroit" },
  { name: "Damascus", country: "Syria", lat: 33.5, lon: 36.3, tz: "Asia/Damascus" },
  { name: "Atlanta, Georgia", country: "United States of America", lat: 33.83, lon: -84.3999, tz: "America/New_York" },
  { name: "Daegu, Taegu-gwangyoksi", country: "South Korea", lat: 35.8668, lon: 128.607, tz: "Asia/Seoul" },
  { name: "Izmir", country: "Turkey", lat: 38.4361, lon: 27.1518, tz: "Europe/Istanbul" },
  { name: "Washington, D.C., District of Columbia", country: "United States of America", lat: 38.8995, lon: -77.0094, tz: "America/New_York" },
  { name: "Hangzhou, Zhejiang", country: "China", lat: 30.25, lon: 120.17, tz: "Asia/Shanghai" },
  { name: "Phoenix, Arizona", country: "United States of America", lat: 33.54, lon: -112.07, tz: "America/Phoenix" },
  { name: "Zhangzhou, Fujian", country: "China", lat: 24.5204, lon: 117.67, tz: "Asia/Shanghai" },
  { name: "Jinan, Shandong", country: "China", lat: 36.675, lon: 116.995, tz: "Asia/Shanghai" },
  { name: "Monterrey, Nuevo León", country: "Mexico", lat: 25.67, lon: -100.33, tz: "America/Monterrey" },
  { name: "Guiyang, Guizhou", country: "China", lat: 26.58, lon: 106.72, tz: "Asia/Chongqing" },
  { name: "Caracas, Distrito Capital", country: "Venezuela", lat: 10.501, lon: -66.917, tz: "America/Caracas" },
  { name: "Nagpur, Maharashtra", country: "India", lat: 21.17, lon: 79.09, tz: "Asia/Kolkata" },
  { name: "Changsha, Hunan", country: "China", lat: 28.2, lon: 112.97, tz: "Asia/Shanghai" },
  { name: "Zhengzhou, Henan", country: "China", lat: 34.755, lon: 113.6651, tz: "Asia/Shanghai" },
  { name: "Mashhad, Razavi Khorasan", country: "Iran", lat: 36.27, lon: 59.57, tz: "Asia/Tehran" },
  { name: "Curitiba, Paraná", country: "Brazil", lat: -25.42, lon: -49.32, tz: "America/Sao_Paulo" },
  { name: "Omdurman, Khartoum", country: "Sudan", lat: 15.6167, lon: 32.48, tz: "Africa/Khartoum" },
  { name: "Lanzhou, Gansu", country: "China", lat: 36.056, lon: 103.792, tz: "Asia/Chongqing" },
  { name: "Qingdao, Shandong", country: "China", lat: 36.09, lon: 120.33, tz: "Asia/Shanghai" },
  { name: "Guayaquil, Guayas", country: "Ecuador", lat: -2.22, lon: -79.92, tz: "America/Guayaquil" },
  { name: "Ibadan, Oyo", country: "Nigeria", lat: 7.38, lon: 3.93, tz: "Africa/Lagos" },
  { name: "Cali, Valle del Cauca", country: "Colombia", lat: 3.4, lon: -76.5, tz: "America/Bogota" },
  { name: "Shijianzhuang, Hebei", country: "China", lat: 38.05, lon: 114.48, tz: "Asia/Shanghai" },
  { name: "Sapporo, Hokkaido", country: "Japan", lat: 43.075, lon: 141.34, tz: "Asia/Tokyo" },
  { name: "Kyiv", country: "Ukraine", lat: 50.4334, lon: 30.5166, tz: "Europe/Kyiv" },
  { name: "Xiangtan, Hunan", country: "China", lat: 27.8504, lon: 112.9, tz: "Asia/Shanghai" },
  { name: "Nanchong, Sichuan", country: "China", lat: 30.7804, lon: 106.13, tz: "Asia/Chongqing" },
  { name: "Aleppo, Aleppo (Halab)", country: "Syria", lat: 36.23, lon: 37.17, tz: "Asia/Damascus" },
  { name: "Kaohsiung, Kaohsiung City", country: "Taiwan", lat: 22.6333, lon: 120.2666, tz: "Asia/Taipei" },
  { name: "Jilin", country: "China", lat: 43.85, lon: 126.55, tz: "Asia/Harbin" },
  { name: "Milan, Lombardia", country: "Italy", lat: 45.47, lon: 9.205, tz: "Europe/Rome" },
  { name: "Nanchang, Jiangxi", country: "China", lat: 28.68, lon: 115.88, tz: "Asia/Shanghai" },
  { name: "Fukuoka", country: "Japan", lat: 33.595, lon: 130.41, tz: "Asia/Tokyo" },
  { name: "San Francisco, California", country: "United States of America", lat: 37.74, lon: -122.46, tz: "America/Los_Angeles" },
  { name: "Havana, Ciudad de la Habana", country: "Cuba", lat: 23.132, lon: -82.3642, tz: "America/Havana" },
  { name: "Tashkent", country: "Uzbekistan", lat: 41.3117, lon: 69.2949, tz: "Asia/Tashkent" },
  { name: "Vienna, Wien", country: "Austria", lat: 48.2, lon: 16.3666, tz: "Europe/Vienna" },
  { name: "Bandung, Jawa Barat", country: "Indonesia", lat: -6.95, lon: 107.57, tz: "Asia/Jakarta" },
  { name: "Accra, Greater Accra", country: "Ghana", lat: 5.55, lon: -0.2167, tz: "Africa/Accra" },
  { name: "Baku, Baki", country: "Azerbaijan", lat: 40.3953, lon: 49.8622, tz: "Asia/Baku" },
  { name: "Athens, Attiki", country: "Greece", lat: 37.9833, lon: 23.7333, tz: "Europe/Athens" },
  { name: "Kunming, Yunnan", country: "China", lat: 25.07, lon: 102.68, tz: "Asia/Chongqing" },
  { name: "Suzhou, Anhui", country: "China", lat: 33.6361, lon: 116.9789, tz: "Asia/Shanghai" },
  { name: "Bekasi, Jakarta Raya", country: "Indonesia", lat: -6.2173, lon: 106.9723, tz: "Asia/Jakarta" },
  { name: "San Diego, California", country: "United States of America", lat: 32.82, lon: -117.18, tz: "America/Los_Angeles" },
  { name: "Medan, Sumatera Utara", country: "Indonesia", lat: 3.58, lon: 98.65, tz: "Asia/Jakarta" },
  { name: "Indore, Madhya Pradesh", country: "India", lat: 22.7151, lon: 75.865, tz: "Asia/Kolkata" },
  { name: "Denver, Colorado", country: "United States of America", lat: 39.7392, lon: -104.984, tz: "America/Denver" },
  { name: "Sanaa, Amanat Al Asimah", country: "Yemen", lat: 15.3547, lon: 44.2066, tz: "Asia/Aden" },
  { name: "Campinas, São Paulo", country: "Brazil", lat: -22.9, lon: -47.1, tz: "America/Sao_Paulo" },
  { name: "Fuzhou, Fujian", country: "China", lat: 26.08, lon: 119.3, tz: "Asia/Shanghai" },
  { name: "Patna, Bihar", country: "India", lat: 25.625, lon: 85.13, tz: "Asia/Kolkata" },
  { name: "Zibo, Shandong", country: "China", lat: 36.8, lon: 118.05, tz: "Asia/Shanghai" },
  { name: "Saidu, N.W.F.P.", country: "Pakistan", lat: 34.75, lon: 72.35, tz: "Asia/Karachi" },
  { name: "Santa Cruz", country: "Bolivia", lat: -17.7539, lon: -63.226, tz: "America/La_Paz" },
  { name: "Bucharest", country: "Romania", lat: 44.4334, lon: 26.0999, tz: "Europe/Bucharest" },
  { name: "Taichung, Taichung City", country: "Taiwan", lat: 24.1521, lon: 120.6817, tz: "Asia/Taipei" },
  { name: "Urumqi, Xinjiang Uygur", country: "China", lat: 43.805, lon: 87.575, tz: "Asia/Urumqi" },
  { name: "Seattle, Washington", country: "United States of America", lat: 47.57, lon: -122.34, tz: "America/Los_Angeles" },
  { name: "Rawalpindi, Punjab", country: "Pakistan", lat: 33.6, lon: 73.04, tz: "Asia/Karachi" },
  { name: "Benoni, Gauteng", country: "South Africa", lat: -26.1496, lon: 28.3299, tz: "Africa/Johannesburg" },
  { name: "Puebla", country: "Mexico", lat: 19.05, lon: -98.2, tz: "America/Mexico_City" },
  { name: "Belem, Pará", country: "Brazil", lat: -1.45, lon: -48.48, tz: "America/Belem" },
  { name: "Frankfurt, Hessen", country: "Germany", lat: 50.1, lon: 8.675, tz: "Europe/Berlin" },
  { name: "Beirut", country: "Lebanon", lat: 33.872, lon: 35.5097, tz: "Asia/Beirut" },
  { name: "Stuttgart, Baden-Württemberg", country: "Germany", lat: 48.78, lon: 9.2, tz: "Europe/Berlin" },
  { name: "Shuyang, Jiangsu", country: "China", lat: 34.1299, lon: 118.7734, tz: "Asia/Shanghai" },
  { name: "Maracaibo, Zulia", country: "Venezuela", lat: 10.73, lon: -71.66, tz: "America/Caracas" },
  { name: "Hamburg", country: "Germany", lat: 53.55, lon: 10, tz: "Europe/Berlin" },
  { name: "Tel Aviv-Yafo, Tel Aviv", country: "Israel", lat: 32.08, lon: 34.77, tz: "Asia/Jerusalem" },
  { name: "Tangshan, Hebei", country: "China", lat: 39.6243, lon: 118.1944, tz: "Asia/Shanghai" },
  { name: "Hefei, Anhui", country: "China", lat: 31.85, lon: 117.28, tz: "Asia/Shanghai" },
  { name: "Warsaw, Masovian", country: "Poland", lat: 52.25, lon: 21, tz: "Europe/Warsaw" },
  { name: "Minsk", country: "Belarus", lat: 53.9, lon: 27.5666, tz: "Europe/Minsk" },
  { name: "Rome, Lazio", country: "Italy", lat: 41.896, lon: 12.4833, tz: "Europe/Rome" },
  { name: "Rabat, Rabat - Salé - Zemmour - Zaer", country: "Morocco", lat: 34.0253, lon: -6.8361, tz: "Africa/Casablanca" },
  { name: "Wanzhou, Chongqing", country: "China", lat: 30.82, lon: 108.4, tz: "Asia/Chongqing" },
  { name: "Budapest", country: "Hungary", lat: 47.5, lon: 19.0833, tz: "Europe/Budapest" },
  { name: "Lisbon, Lisboa", country: "Portugal", lat: 38.7227, lon: -9.1449, tz: "Europe/Lisbon" },
  { name: "Bhopal, Madhya Pradesh", country: "India", lat: 23.25, lon: 77.41, tz: "Asia/Kolkata" },
  { name: "Xuzhou, Jiangsu", country: "China", lat: 34.28, lon: 117.18, tz: "Asia/Shanghai" },
  { name: "Sendai, Miyagi", country: "Japan", lat: 38.2871, lon: 141.0217, tz: "Asia/Tokyo" },
  { name: "Manaus, Amazonas", country: "Brazil", lat: -3.1, lon: -60, tz: "America/Manaus" },
  { name: "Birmingham, West Midlands", country: "United Kingdom", lat: 52.475, lon: -1.92, tz: "Europe/London" },
  { name: "Kyoto", country: "Japan", lat: 35.03, lon: 135.75, tz: "Asia/Tokyo" },
  { name: "Taian, Shandong", country: "China", lat: 36.2, lon: 117.1201, tz: "Asia/Shanghai" },
  { name: "Douala, Littoral", country: "Cameroon", lat: 4.0604, lon: 9.71, tz: "Africa/Douala" },
  { name: "Naples, Campania", country: "Italy", lat: 40.84, lon: 14.245, tz: "Europe/Rome" },
  { name: "Port-au-Prince, Ouest", country: "Haiti", lat: 18.541, lon: -72.336, tz: "America/Port-au-Prince" },
  { name: "Irvine, California", country: "United States of America", lat: 33.6804, lon: -117.83, tz: "America/Los_Angeles" },
  { name: "George Town, Pulau Pinang", country: "Malaysia", lat: 5.4136, lon: 100.3294, tz: "Asia/Kuala_Lumpur" },
  { name: "Wenzhou, Zhejiang", country: "China", lat: 28.02, lon: 120.6501, tz: "Asia/Shanghai" },
  { name: "Haikou, Hainan", country: "China", lat: 20.05, lon: 110.32, tz: "Asia/Chongqing" },
  { name: "Ludhiana, Punjab", country: "India", lat: 30.9278, lon: 75.8723, tz: "Asia/Kolkata" },
  { name: "Goiania, Goiás", country: "Brazil", lat: -16.72, lon: -49.3, tz: "America/Sao_Paulo" },
  { name: "Palembang, Sumatera Selatan", country: "Indonesia", lat: -2.98, lon: 104.75, tz: "Asia/Jakarta" },
  { name: "Hiroshima", country: "Japan", lat: 34.3878, lon: 132.4429, tz: "Asia/Tokyo" },
  { name: "Vadodara, Dadra and Nagar Haveli", country: "India", lat: 22.31, lon: 73.18, tz: "Asia/Kolkata" },
  { name: "Kalyan, Maharashtra", country: "India", lat: 19.2502, lon: 73.1602, tz: "Asia/Kolkata" },
  { name: "Isfahan, Esfahan", country: "Iran", lat: 32.7, lon: 51.7, tz: "Asia/Tehran" },
  { name: "Tunis", country: "Tunisia", lat: 36.8028, lon: 10.1797, tz: "Africa/Tunis" },
  { name: "Valencia, Carabobo", country: "Venezuela", lat: 10.23, lon: -67.98, tz: "America/Caracas" },
  { name: "Harare", country: "Zimbabwe", lat: -17.8178, lon: 31.0447, tz: "Africa/Harare" },
  { name: "Luoyang, Henan", country: "China", lat: 34.68, lon: 112.4701, tz: "Asia/Shanghai" },
  { name: "Quito, Pichincha", country: "Ecuador", lat: -0.215, lon: -78.5001, tz: "America/Guayaquil" },
  { name: "Xiamen, Fujian", country: "China", lat: 24.45, lon: 118.08, tz: "Asia/Shanghai" },
  { name: "Antananarivo", country: "Madagascar", lat: -18.9166, lon: 47.5166, tz: "Indian/Antananarivo" },
  { name: "Luzhou, Sichuan", country: "China", lat: 28.88, lon: 105.38, tz: "Asia/Chongqing" },
]

export const CITIES: City[] = [...CURATED, ...TOP_BY_POPULATION]
